name: Zahmoul.net
favicon: null
layout_spectrum: 0.1482897917740047
typography_spectrum: 0.7410125974565744
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5640998387243599
  lightness: 0.7667980438563973
  saturation: 0.6135190357454121
  rhythmicContrast: 0.8844435086939484
purpose: []
